name: golangci-lint
on:
  push:
    tags:
    - v*
    branches:
    - master
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with: # Required: the version of golangci-lint is required and must be specified without a patch version:
        # we always use the latest patch version.
        version: v1.54
        # Optional: if set to `true` then the all caching functionality will be complete disabled,
        #           takes precedence over all other caching options.
        skip-cache: true
        args: --issues-exit-code=1
        only-new-issues: true